//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetTalk.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class NetTalkEntities : DbContext
    {
        public NetTalkEntities()
            : base("name=NetTalkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TbAlerts> TbAlerts { get; set; }
        public DbSet<TbFriend> TbFriend { get; set; }
        public DbSet<TbLogs> TbLogs { get; set; }
        public DbSet<TbMessage> TbMessage { get; set; }
        public DbSet<TbUsers> TbUsers { get; set; }
        public DbSet<TbUserStatus> TbUserStatus { get; set; }
        public DbSet<TbVcard> TbVcard { get; set; }
        public DbSet<VwFriend> VwFriend { get; set; }
        public DbSet<VwLog> VwLog { get; set; }
        public DbSet<VwMessage> VwMessage { get; set; }
        public DbSet<VwMessageOffline> VwMessageOffline { get; set; }
        public DbSet<VwUsers> VwUsers { get; set; }
    
        public virtual int DeleteUser(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUser", userIdParameter);
        }
    }
}
