//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetTalk.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbAlerts
    {
        public System.Guid AlertId { get; set; }
        public string AlertText { get; set; }
        public System.TimeSpan AlertTime { get; set; }
        public string AlertHTML { get; set; }
    }
}
