//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetTalk.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbUsers
    {
        public TbUsers()
        {
            this.TbFriend = new HashSet<TbFriend>();
            this.TbFriend1 = new HashSet<TbFriend>();
            this.TbMessage = new HashSet<TbMessage>();
            this.TbMessage1 = new HashSet<TbMessage>();
        }
    
        public System.Guid UserId { get; set; }
        public string Username { get; set; }
        public string UserPassCrypt { get; set; }
        public string UserPassSalt { get; set; }
        public Nullable<System.DateTime> UserLastLoginDate { get; set; }
        public Nullable<System.DateTime> UserPrevLoginDate { get; set; }
        public Nullable<System.DateTime> UserLastChangePass { get; set; }
        public bool UserWebAdmin { get; set; }
    
        public virtual ICollection<TbFriend> TbFriend { get; set; }
        public virtual ICollection<TbFriend> TbFriend1 { get; set; }
        public virtual ICollection<TbMessage> TbMessage { get; set; }
        public virtual ICollection<TbMessage> TbMessage1 { get; set; }
        public virtual TbUserStatus TbUserStatus { get; set; }
        public virtual TbVcard TbVcard { get; set; }
    }
}
