//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetTalk.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwFriend
    {
        public System.Guid UserId { get; set; }
        public System.Guid FriendId { get; set; }
        public string GroupName { get; set; }
        public string FriendUserName { get; set; }
        public Nullable<short> UserStatus { get; set; }
        public string UserStatusText { get; set; }
        public string VcardFirstName { get; set; }
        public string VcardLastName { get; set; }
        public string VcardPhoto { get; set; }
        public string VcardOrgName { get; set; }
        public string VcardOrgUnit { get; set; }
        public byte FriendStatus { get; set; }
        public string Username { get; set; }
        public Nullable<bool> UserIsOnline { get; set; }
    }
}
