//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetTalk.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwLog
    {
        public System.Guid LogId { get; set; }
        public string LogText { get; set; }
        public System.DateTime LogDate { get; set; }
        public string LogSessionId { get; set; }
        public Nullable<System.Guid> LogUserId { get; set; }
        public string Username { get; set; }
        public string VcardFirstName { get; set; }
        public string VcardLastName { get; set; }
        public string VcardPhoto { get; set; }
    }
}
