//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace NetTalk.Web.Codes.XMLConfig {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class config {
        
        private string organizationField;
        
        private bool serverupField;
        
        private string domainField;
        
        private string pathField;
        
        private configLastlogclear lastlogclearField;
        
        private configAccess accessField;
        
        /// <remarks/>
        public string organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public bool serverup {
            get {
                return this.serverupField;
            }
            set {
                this.serverupField = value;
            }
        }
        
        /// <remarks/>
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public configLastlogclear lastlogclear {
            get {
                return this.lastlogclearField;
            }
            set {
                this.lastlogclearField = value;
            }
        }
        
        /// <remarks/>
        public configAccess access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class configLastlogclear {
        
        private ushort yearField;
        
        private byte monthField;
        
        /// <remarks/>
        public ushort year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public byte month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class configAccess {
        
        private bool changepicField;
        
        private bool changestatusField;
        
        private bool changepassField;
        
        /// <remarks/>
        public bool changepic {
            get {
                return this.changepicField;
            }
            set {
                this.changepicField = value;
            }
        }
        
        /// <remarks/>
        public bool changestatus {
            get {
                return this.changestatusField;
            }
            set {
                this.changestatusField = value;
            }
        }
        
        /// <remarks/>
        public bool changepass {
            get {
                return this.changepassField;
            }
            set {
                this.changepassField = value;
            }
        }
    }
}
